### ISSUE TITLE
Tracking issue for current spurious CI failures

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1540]
The issues below prevent consistently clean CI runs that need to be re-triggered by maintainers until they complete

- [x] https://github.com/tgstation/tgstation-server/issues/1539
- [ ] https://github.com/tgstation/tgstation-server/issues/1529
- [x] https://github.com/tgstation/tgstation-server/issues/1541
