### ISSUE TITLE
`V6` dev merge finalization checklist

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1589]
- [x] Update documentation for setting up OpenDream (esp on Linux)
- [x] Revert commit baa908f0b2
- [x] Revert commit 2f9fb5df0c66a20960c3472c2dcb45bdbc2980c6 #1728
- [x] Replace preview nuget packages with real ones #1728 
- [x] Replace preview CI installs with real ones. #1716
- [x] Re-enable proper .deb dependencies #1716
