### ISSUE TITLE
`V6` finalization checklist

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1674]
- [x] #1589
- [x] #1313 
- [x] Revert commit baa908f0b2: e99cb6ba4054e2785de3b27a5ab09b2ed701cd0e
- [x] Release DMAPI, HTTP API, and Nuget Packages: 01cda70d2e669b78bb9c43d22268c4935130b776
- [x] Merge Webpanel Update: https://github.com/tgstation/tgstation-server-webpanel/pull/155
- [x] Update webpanel
- [x] Merge final release! #1748
